[theme]
primaryColor = "#1a73e8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = true
enableCORS = false  # Disable Cross-Origin Resource Sharing if not needed, can slightly improve performance
enableWebsocketCompression = false  # Reduce latency by disabling websocket compression if it's not necessary
maxUploadSize = 200  # Increase if your app handles large uploads, default is 200MB
enableCORS = false
enableWebsocketCompression = false

[ui]
hideSidebarNav = true

[layout]
wide = true

[logger]
level = "error"  # Reduce log verbosity to only show errors, reduces processing time spent on logging

[runner]
magicEnabled = false  # Disables magic commands which may reduce processing overhead
